import { getSupabase } from '../supabase';
import { diffFieldIds } from '../domain/fields';
import { normalizePage, type ResearchPage } from '../domain/page';
import type { ResearchEntry, ResearchEntryCard, ResearchExternalAuthor } from '../domain/types';

/* eslint-disable @typescript-eslint/no-explicit-any */

// Member-created research entries (the DB-backed feature formerly called
// "projects"). Curated editorial research lives in ./research.ts.

/** All published research entries. Empty on no backend. */
export async function listResearchEntries(): Promise<ResearchEntryCard[]> {
  const sb = getSupabase();
  if (!sb) return [];
  let data: any, error: any;
  try {
    ({ data, error } = await sb
      .from('research')
      .select('id, public_id, title, avatar_url')
      .eq('is_published', true));
  } catch {
    return [];
  }
  if (error || !data) return [];
  return data.map((r: any) => ({
    id: r.id,
    publicId: r.public_id,
    title: r.title,
    avatarUrl: r.avatar_url,
  }));
}

/** Public URL for a file in the research-files bucket ('#' with no backend). */
export function researchFileUrl(storagePath: string): string {
  const sb = getSupabase();
  return sb ? sb.storage.from('research-files').getPublicUrl(storagePath).data.publicUrl : '#';
}

/** One research entry's full detail by public_id, or null if not found / no backend. */
export async function getResearchEntry(publicId: string): Promise<ResearchEntry | null> {
  const sb = getSupabase();
  if (!sb) return null;
  let data: any, error: any;
  try {
    ({ data, error } = await sb
      .from('research')
      .select(
        `id, public_id, title, description, avatar_url, is_published, external_authors, page,
       research_fields(field_id, fields(name)),
       research_members(role, sort_order, people(id, public_id, full_name, avatar_color)),
       research_links(id, label, url, sort_order),
       research_files(id, storage_path, kind, caption, sort_order)`,
      )
      .eq('public_id', publicId)
      .single());
  } catch {
    return null; // network/backend unreachable → honest fallback
  }
  if (error || !data) return null;
  const d = data as any;
  return {
    dbId: d.id,
    publicId: d.public_id,
    title: d.title,
    description: d.description ?? '',
    avatarUrl: d.avatar_url,
    published: d.is_published,
    fields: (d.research_fields ?? []).map((f: any) => f.fields?.name).filter(Boolean),
    fieldIds: (d.research_fields ?? []).map((f: any) => f.field_id),
    page: normalizePage(d.page),
    externalAuthors: Array.isArray(d.external_authors)
      ? d.external_authors.map((a: any) => ({ name: String(a?.name ?? ''), role: a?.role }))
      : [],
    members: (d.research_members ?? [])
      .filter((m: any) => m.people)
      .sort((a: any, b: any) => (a.sort_order ?? 0) - (b.sort_order ?? 0))
      .map((m: any) => ({
        id: m.people.id,
        publicId: m.people.public_id,
        name: m.people.full_name,
        role: m.role || 'Member',
        color: m.people.avatar_color,
      })),
    links: (d.research_links ?? [])
      .map((l: any) => ({ id: l.id, label: l.label, url: l.url, sortOrder: l.sort_order }))
      .sort((a: any, b: any) => a.sortOrder - b.sortOrder),
    files: (d.research_files ?? [])
      .map((f: any) => ({
        id: f.id,
        storagePath: f.storage_path,
        kind: f.kind,
        caption: f.caption,
        sortOrder: f.sort_order,
      }))
      .sort((a: any, b: any) => a.sortOrder - b.sortOrder),
  };
}

// --------------------------------------------------------------- writes ----
// RLS gates all of these: creation needs `is_org_member()` + `created_by =
// my_person_id()`; every later write needs `is_project_editor(id)` (the creator
// is auto-added to research_members by trigger, so they qualify immediately).

export interface ResearchPatch {
  title: string;
  description: string;
  /** the URL key after `?id=` — unique, lowercase-dashed (DB CHECK) */
  publicId: string;
}

/** Create a draft research entry. public_id is generated by a trigger, and the
 *  creator is auto-added as its first member. Returns the new public_id. */
export async function createResearchEntry(
  title: string,
  personId: string,
): Promise<{ publicId: string | null; error: string | null }> {
  const sb = getSupabase();
  if (!sb) return { publicId: null, error: 'no backend' };
  try {
    const { data, error } = await sb
      .from('research')
      .insert({ title, created_by: personId })
      .select('public_id')
      .single();
    if (error) return { publicId: null, error: error.message };
    return { publicId: (data as any).public_id, error: null };
  } catch (e: any) {
    return { publicId: null, error: e?.message ?? 'could not create' };
  }
}

/** Save title + description. */
export async function updateResearchEntry(
  dbId: string,
  patch: ResearchPatch,
): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb
      .from('research')
      .update({
        title: patch.title,
        description: patch.description || null,
        public_id: patch.publicId,
      })
      .eq('id', dbId);
    if (error) {
      // unique violation on public_id — there is no availability RPC for
      // research (is_public_id_available only covers people), so the constraint
      // is the check and this is the friendly translation of it.
      return /duplicate key|research_public_id_key|23505/.test(
        `${error.message} ${(error as any).code ?? ''}`,
      )
        ? 'that URL is already taken'
        : error.message;
    }
    return null;
  } catch (e: any) {
    return e?.message ?? 'save failed';
  }
}

/** Publish / unpublish an entry. */
export async function setResearchPublished(dbId: string, next: boolean): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb.from('research').update({ is_published: next }).eq('id', dbId);
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'failed';
  }
}

/** Reconcile research_fields to match `selected` (diff against `before`). */
export async function syncResearchFields(
  dbId: string,
  before: number[],
  selected: number[],
): Promise<void> {
  const sb = getSupabase();
  if (!sb) return;
  const { toAdd, toRemove } = diffFieldIds(before, selected);
  try {
    if (toAdd.length) {
      await sb
        .from('research_fields')
        .insert(toAdd.map((field_id) => ({ research_id: dbId, field_id })));
    }
    if (toRemove.length) {
      await sb.from('research_fields').delete().eq('research_id', dbId).in('field_id', toRemove);
    }
  } catch (e) {
    console.error('ideaLab: syncResearchFields failed', e);
  }
}

/** Add an external link. The DB CHECK requires an http(s) URL. */
export async function addResearchLink(
  dbId: string,
  label: string,
  url: string,
  sortOrder = 0,
): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb
      .from('research_links')
      .insert({ research_id: dbId, label, url, sort_order: sortOrder });
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'could not add link';
  }
}

export async function deleteResearchLink(linkId: string): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb.from('research_links').delete().eq('id', linkId);
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'could not remove link';
  }
}

/** Delete the whole entry (cascades to members/fields/links/files). */
export async function deleteResearchEntry(dbId: string): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb.from('research').delete().eq('id', dbId);
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'could not delete';
  }
}

/** Add a co-member (an editor) to a research entry. */
export async function addResearchMember(
  dbId: string,
  personId: string,
  role: string,
  sortOrder = 0,
): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb.from('research_members').insert({
      research_id: dbId,
      person_id: personId,
      role: role || 'Member',
      sort_order: sortOrder,
    });
    if (error) {
      return String((error as any).code) === '23505' ? 'they are already a member' : error.message;
    }
    return null;
  } catch (e: any) {
    return e?.message ?? 'could not add member';
  }
}

/**
 * Remove a co-member. NOTE: a trigger deletes the whole entry when its last
 * member leaves — callers should refuse to remove the only one.
 */
export async function removeResearchMember(dbId: string, personId: string): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb
      .from('research_members')
      .delete()
      .eq('research_id', dbId)
      .eq('person_id', personId);
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'could not remove member';
  }
}

/** Replace the external-collaborator list (display-only credits). */
export async function setExternalAuthors(
  dbId: string,
  authors: ResearchExternalAuthor[],
): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb
      .from('research')
      .update({ external_authors: authors })
      .eq('id', dbId);
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'could not save collaborators';
  }
}

/** Change a member's role. Any member may edit any other member's role. */
export async function updateResearchMemberRole(
  dbId: string,
  personId: string,
  role: string,
): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb
      .from('research_members')
      .update({ role: role || 'Member' })
      .eq('research_id', dbId)
      .eq('person_id', personId);
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'could not save role';
  }
}

/** Save the composed block page (pass null to clear it). */
export async function updateResearchPage(
  dbId: string,
  page: ResearchPage | null,
): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    const { error } = await sb.from('research').update({ page }).eq('id', dbId);
    return error?.message ?? null;
  } catch (e: any) {
    return e?.message ?? 'could not save the page';
  }
}

/** Persist a new member order: sort_order = position in `personIds`. */
export async function setResearchMembersOrder(
  dbId: string,
  personIds: string[],
): Promise<string | null> {
  const sb = getSupabase();
  if (!sb) return 'no backend';
  try {
    for (let i = 0; i < personIds.length; i++) {
      const { error } = await sb
        .from('research_members')
        .update({ sort_order: i })
        .eq('research_id', dbId)
        .eq('person_id', personIds[i]);
      if (error) return error.message;
    }
    return null;
  } catch (e: any) {
    return e?.message ?? 'could not save the order';
  }
}
